services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - perf

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - perf
    depends_on:
      - influxdb

  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./scripts:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - perf
    depends_on:
      - influxdb

networks:
  perf:
    driver: bridge

volumes:
  influxdb:
  grafana_data: